
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrzuifckyctcncvpokcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyenVpZmNreWN0Y25jdnBva2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MzA0MTksImV4cCI6MjA1OTQwNjQxOX0.MFrDXaq6wv_rGbK7Ntdbt7_BYHgxc3ZH40xNpol6X-Y";

// Create a more permissive Supabase client that allows for dynamic table access
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// This is a typed client for tables that are defined in the Database type
export const typedSupabase = supabase;

// To use Supabase realtime features
export const enableRealtimeFor = (tables: string[]) => {
  const channel = supabase.channel('schema-db-changes');
  
  tables.forEach(table => {
    channel.on(
      'postgres_changes',
      { event: '*', schema: 'public', table },
      (payload) => console.log(payload)
    );
  });
  
  return channel.subscribe();
};

// Helper for safely accessing tables that might not be in the type definition
export const safeTable = <T = any>(tableName: string) => {
  // @ts-ignore - We're deliberately bypassing type checking here
  return supabase.from(tableName) as any;
};
